### ISSUE TITLE
Not signed in?

### ISSUE THREAD

**Issue by johnpena** [suryasev/unofficial-google-trends-api#1]
I tried running this code with the example from your blog:

```
connector = pyGTrends('myemail@gmail.com','blackalicious')
connector.download_report(('blekko',))
print connector.raw_data
```

The response:
"You must be signed in to export data from Google Trends"

**Comment by suryasev** [comment]
Hey jcp,
I'm reluctant to experiment logging in with your account.
However, I tested the code with a different email address and password and there are no problems.  Are you sure you don't just have an incorrect password or typo in your email address?

**Comment by johnpena** [comment]
You're welcome to try with this email address, it's a mule account. blackbriarproject100@gmail.com, blackalicious. No dice with that or with my personal email address.

**Comment by pcorliss** [comment]
I'm receiving the same error. Different machines, networks and accounts all throw the same error.

[pcorliss@hooch orig]$ python basic_test.py 
You must be signed in to export data from Google Trends
[pcorliss@hooch orig]$ cat basic_test.py 
from pyGTrends import pyGTrends

connector = pyGTrends('xxxxxxx@gmail.com','xxxxxxx')
connector.download_report(('foo',))
print connector.raw_data

**Comment by suryasev** [comment]
Alright.
It turns out that Google changed their Login algorithm.  Where in the past I could construct a unique 11-digit ID out of thin air, the new algorithm matched the 11-digit ID against one written into a cookie.  

The reason why jcp20 was failing _some_ of the time is probably due to Google rolling out their new login algorithm, and some of the calls would hit an older server, while others would fail on a new server.

I have also simplified the convenience functions, with the expectation that the user uses the csv.reader or the csv.DictReader features of the standard library.

Recommended example:
    from csv import DictReader
    r = pyGTrends(username, password)
    r.download_report(('pants', 'skirt'))
    d = DictReader(r.csv().split('\n'))

**Comment by johnpena** [comment]
Just tested it out, works for me. Thanks for the update!
